sudo: required
services:
    - docker

before_install:
    - docker build -t s2bnwebsite/tests -f ./tests/Dockerfile.dev ./tests

script:
    - docker run -e CI=true s2bnwebsite/tests

after_success:
    - docker build -t s2bnwebsite/multi-server ./server
    - docker build -t s2bnwebsite/multi-nginx ./nginx
    - docker build -t s2bnwebsite/multi-client ./client
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push s2bnwebsite/multi-client
    - docker push s2bnwebsite/multi-server
    - docker push s2bnwebsite/multi-nginx 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-284053812947
    bucket_path: docker_multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


    